### ISSUE TITLE
Boolean runtime objects throw errors when operated on

### ISSUE THREAD

**Issue by ncatelli** [ncatelli/rlox#73]
```> print true;
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', librlox/src/parser/expression_parser.rs:214:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ncatelli** [comment]
affects nil too

```
> print nil;
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', librlox/src/parser/expression_parser.rs:214:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
